"""
Django settings for hashflix project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/




import os 

TOKEN_CSRF = os.getenv('TOKEN_CSRF')
if TOKEN_CSRF:
    SECRET_KEY = TOKEN_CSRF
    CSRF_TRUSTED_ORIGINS = ['https://python-django-hashflix-production.up.railway.app', 'http://localhost:8000']
else:
    SECRET_KEY = "django-insecure-7i@jny5hv42*7v))zl9mnpm+)6s05u%8&o0$rww2)m+yfek_sh"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['python-django-hashflix-production.up.railway.app','localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'filme',
    'crispy_forms',
    'crispy_bootstrap5',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hashflix.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ['templates'], ## não esqueça de criar a pasta templates no raiz do projeto!
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                ## aqui indicamos o app filme, conforme a pasta, veja o arquivo novos_context.py e dentro pego a função
                'filme.novos_context.lista_filmes_recentes',
                'filme.novos_context.lista_filmes_emalta',
                'filme.novos_context.filme_destaque',

               
            ],
        },
    },
]

WSGI_APPLICATION = "hashflix.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}
import dj_database_url

DATABASES_URL = os.getenv('DATABASE_URL')
if DATABASES_URL:
    
    DATABASES = {
        'default' : dj_database_url.config(default=DATABASES_URL, conn_max_age=600)
        }
    
## Aqui estamos indicando que o modelo de usuário personalizado é o modelo Usuario que criamos no app filme, e que herda de AbstractUser.
AUTH_USER_MODEL = 'filme.Usuario'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
## aqui é a pasta onde os arquivos estáticos serão coletados quando rodarmos o comando collectstatic, 
# veja o arquivo wsgi.py para mais detalhes.
STATIC_ROOT =BASE_DIR /'staticfiles' 

STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = 'media/'
MEDIA_ROOT =BASE_DIR /'media'

##########################################################################################
# Aqui estamos indicando para onde o usuário deve ser redirecionado 
# após fazer login, e para onde deve ser redirecionado caso tente acessar 
# uma página que requer login sem estar autenticado.
# o filme indica o nome APP e o homefilmes indica o nome da url, 
# veja o arquivo urls.py do app filme.
LOGIN_REDIRECT_URL = 'filme:homefilmes'
# Aqui é a url para onde o usuário deve ser redirecionado caso tente acessar 
# uma página que requer login sem estar autenticado.
LOGIN_URL= 'filme:login'

# MAIS DETALHES EM https://github.com/django-crispy-forms/crispy-bootstrap5

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'
