# Generated by Django 6.0.2 on 2026-02-19 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("thumb", models.ImageField(upload_to="thumbs_filmes/")),
                ("descricao", models.TextField(max_length=1000)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("acao", "Ação"),
                            ("comedia", "Comédia"),
                            ("drama", "Drama"),
                            ("terror", "Terror"),
                            ("ficcao", "Ficção Científica"),
                            ("animacao", "Animação"),
                            ("aventura", "Aventura"),
                            ("romance", "Romance"),
                            ("documentario", "Documentário"),
                        ],
                        max_length=20,
                    ),
                ),
                ("visualizacoes", models.IntegerField(default=0)),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
